server:
  port: 443
  cert: server.crt
  key: server.key
  phone: 1234567890
hcaptcha:
  sitekey: aaaaaaaaaaaaaaaaa
  secret: aaaaaaaaaaaaaaaaa
mysql:
  host: db.domain.tld
  port: 12345
  database: signup
  username: admin
  password: aaaaaaaaaaaaaaaaaaaaaaaaaa
  ca: ca-certificate.crt